# Generated by Django 4.0.4 on 2022-05-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=150)),
                ('quote', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='doctor_images')),
            ],
        ),
    ]
