# Generated by Django 4.0.4 on 2022-05-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='name',
            new_name='quote_name',
        ),
    ]
